name: beakerx
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - openjdk=11
  - notebook>=5.7.6
  - tornado>6
  - ipywidgets>=7.5.1
  - maven
  - py4j
  - pyspark
  - bottle
  - requests
  - numpy
  - pandas
  - jupyterlab=2
